first_name: "Ferdaous"
last_name: "Masmoudi"
title: "PhD in Electrical Engineering"
contact_note: "contact information"
description: "about research"
email: "ferdaous.masmoudi@gmail.com"
phone: "+216 23 605 813"
homepage: "ferdaousmasmoudi.github.io"
social:
  ORCID: "0000-0001-8457-7162"
  ResearchGate: "Ferdaous-Masmoudi"
  LinkedIn: "ferdaous-masmoudi-2a95b64a"
  GitHub: "ferdaousmasmoudi"
url: "https://ferdaousmasmoudi.github.io"
baseurl: ""